version: '3.1'

services:
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8090:8080
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: super_secret
    ports:
      - 6543:5432
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data