//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

pub use super::label::Entity as Label;
pub use super::social_profile::Entity as SocialProfile;
pub use super::task::Entity as Task;
pub use super::task_group::Entity as TaskGroup;
pub use super::user::Entity as User;
pub use super::workspace::Entity as Workspace;
