//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "social_provider_type"
)]
pub enum SocialProviderType {
    #[sea_orm(string_value = "discord")]
    Discord,
    #[sea_orm(string_value = "google")]
    Google,
}
