//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "task")]
pub struct Model {
    pub task_group_id: i32,
    pub title: String,
    pub description: String,
    pub labels_ids: Option<Vec<i32>>,
    #[sea_orm(primary_key)]
    pub id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::task_group::Entity",
        from = "Column::TaskGroupId",
        to = "super::task_group::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TaskGroup,
}

impl Related<super::task_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TaskGroup.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
